-- auto-generated by tools/sprotogen.py -- do not edit

local M = {}

M._PROTO_HASH = "0d96884cbc9728dbf49eaec3eadd54d8fe0b2dc4ed5ddc489538b86639bfc4fe"

-- ======== c2s Protocol Tags ========
-- bag
M.BAG_LIST = 30
M.BAG_ADD = 31
M.BAG_REMOVE = 32
M.BAG_USE = 33
M.BAG_SORT = 34

-- chat
M.CHAT_SEND = 40
M.CHAT_HISTORY = 41

-- common
M.PING = 4
M.ENTER_SCENE = 10
M.MOVE = 11

-- login
M.LOGIN = 1
M.REGISTER = 2

-- rank
M.RANK_TOP = 50
M.RANK_SELF = 51

-- ======== s2c Protocol Tags ========
-- chat
M.CHAT_NOTIFY = 10
M.CHAT_MESSAGE = 11

-- common
M.ERROR = 1

-- ======== Name ↔ Tag Mapping ========
local name_to_tag = {}
name_to_tag["bag_list"] = 30
name_to_tag["bag_add"] = 31
name_to_tag["bag_remove"] = 32
name_to_tag["bag_use"] = 33
name_to_tag["bag_sort"] = 34
name_to_tag["chat_send"] = 40
name_to_tag["chat_history"] = 41
name_to_tag["chat_notify"] = 10
name_to_tag["chat_message"] = 11
name_to_tag["ping"] = 4
name_to_tag["enter_scene"] = 10
name_to_tag["move"] = 11
name_to_tag["error"] = 1
name_to_tag["login"] = 1
name_to_tag["register"] = 2
name_to_tag["rank_top"] = 50
name_to_tag["rank_self"] = 51
M._name_to_tag = name_to_tag

-- ======== Handler Registry ========
local handlers = {}

function M.register(name, fn)
    assert(type(name) == "string" and type(fn) == "function",
        "proto.register: expected (string, function)")
    handlers[name] = fn
end

function M.register_module(module_name, handler_table)
    assert(type(handler_table) == "table",
        "proto.register_module: expected table of handlers")
    for name, fn in pairs(handler_table) do
        assert(type(fn) == "function",
            string.format("proto.register_module: handler '%s' must be a function", name))
        handlers[name] = fn
    end
end

function M.dispatch(name, ctx, ...)
    local fn = handlers[name]
    if fn then
        return fn(ctx, ...)
    end
    return nil, "unknown protocol: " .. tostring(name)
end

function M.has_handler(name)
    return handlers[name] ~= nil
end

return M
