// auto-generated by tools/sprotogen.py -- do not edit

export const PROTO_HASH = "0d96884cbc9728dbf49eaec3eadd54d8fe0b2dc4ed5ddc489538b86639bfc4fe";

// ======== Protocol Tag Constants ========
export const enum ProtoTag {
    // bag
    BAG_LIST = 30,
    BAG_ADD = 31,
    BAG_REMOVE = 32,
    BAG_USE = 33,
    BAG_SORT = 34,

    // chat
    CHAT_SEND = 40,
    CHAT_HISTORY = 41,
    CHAT_NOTIFY = 10,
    CHAT_MESSAGE = 11,

    // common
    PING = 4,
    ENTER_SCENE = 10,
    MOVE = 11,
    ERROR = 1,

    // login
    LOGIN = 1,
    REGISTER = 2,

    // rank
    RANK_TOP = 50,
    RANK_SELF = 51,

}

// ======== Shared Types ========

export interface ItemEntry
{
    uid: string;
    item_id: number;
    count: number;
    position: number;
    equipped: boolean;
    extra: string;
}

export interface EffectEntry
{
    type: string;
    value: number;
}

export interface ChatMessageEntry
{
    from_id: number;
    from_name: string;
    msg: string;
    timestamp: number;
}

export interface Package
{
    type: number;
    session: number;
}

export interface RankEntry
{
    rank: number;
    player_id: number;
    nickname: string;
    score: number;
}

// ======== C2S Request/Response ========

// bag_list (tag=30, c2s)
export interface BagListResponse
{
    ok: boolean;
    items: ItemEntry[];
    gold: number;
    capacity: number;
}

// bag_add (tag=31, c2s)
export interface BagAddRequest
{
    item_id: number;
    count: number;
}

export interface BagAddResponse
{
    ok: boolean;
    items: ItemEntry[];
}

// bag_remove (tag=32, c2s)
export interface BagRemoveRequest
{
    uid: string;
    count: number;
}

export interface BagRemoveResponse
{
    ok: boolean;
}

// bag_use (tag=33, c2s)
export interface BagUseRequest
{
    uid: string;
    count: number;
}

export interface BagUseResponse
{
    ok: boolean;
    effects: EffectEntry[];
}

// bag_sort (tag=34, c2s)
export interface BagSortResponse
{
    ok: boolean;
    items: ItemEntry[];
}

// chat_send (tag=40, c2s)
export interface ChatSendRequest
{
    channel: number;
    target_id: number;
    msg: string;
}

export interface ChatSendResponse
{
    ok: boolean;
}

// chat_history (tag=41, c2s)
export interface ChatHistoryRequest
{
    channel: number;
    count: number;
}

export interface ChatHistoryResponse
{
    ok: boolean;
    messages: ChatMessageEntry[];
}

// enter_scene (tag=10, c2s)
export interface EnterSceneRequest
{
    scene_id: number;
}

export interface EnterSceneResponse
{
    ok: boolean;
}

// move (tag=11, c2s)
export interface MoveRequest
{
    x: number;
    y: number;
}


// login (tag=1, c2s)
export interface LoginRequest
{
    account: string;
    password: string;
}

export interface LoginResponse
{
    ok: boolean;
    player_id: number;
    token: string;
    nickname: string;
    level: number;
}

// register (tag=2, c2s)
export interface RegisterRequest
{
    account: string;
    password: string;
}

export interface RegisterResponse
{
    ok: boolean;
    player_id: number;
}

// rank_top (tag=50, c2s)
export interface RankTopRequest
{
    board_type: string;
    top_n: number;
}

export interface RankTopResponse
{
    ok: boolean;
    entries: RankEntry[];
    update_time: number;
}

// rank_self (tag=51, c2s)
export interface RankSelfRequest
{
    board_type: string;
}

export interface RankSelfResponse
{
    ok: boolean;
    rank: number;
    score: number;
    total: number;
}

// ======== S2C Push ========

// chat_notify (tag=10, s2c)
export interface ChatNotifyResponse
{
    player_id: number;
    msg: string;
}

// chat_message (tag=11, s2c)
export interface ChatMessageResponse
{
    channel: number;
    from_id: number;
    from_name: string;
    msg: string;
    timestamp: number;
}

// error (tag=1, s2c)
export interface ErrorResponse
{
    code: number;
    msg: string;
}