// auto-generated by tools/sprotogen.py -- do not edit
namespace Game.Protocol
{
    /// <summary>
    /// 协议指纹 SHA-256（用于运行时版本校验）
    /// </summary>
    public const string ProtoHash = "0d96884cbc9728dbf49eaec3eadd54d8fe0b2dc4ed5ddc489538b86639bfc4fe";

    /// <summary>
    /// 协议标签常量
    /// </summary>
    public static class ProtoTag
    {
        // bag
        public const int BAG_LIST = 30;
        public const int BAG_ADD = 31;
        public const int BAG_REMOVE = 32;
        public const int BAG_USE = 33;
        public const int BAG_SORT = 34;

        // chat
        public const int CHAT_SEND = 40;
        public const int CHAT_HISTORY = 41;
        public const int CHAT_NOTIFY = 10;
        public const int CHAT_MESSAGE = 11;

        // common
        public const int PING = 4;
        public const int ENTER_SCENE = 10;
        public const int MOVE = 11;
        public const int ERROR = 1;

        // login
        public const int LOGIN = 1;
        public const int REGISTER = 2;

        // rank
        public const int RANK_TOP = 50;
        public const int RANK_SELF = 51;

    }

    // ======== 共享类型 ========

    [System.Serializable]
    public class ItemEntry
    {
        /// <summary>tag=0, type=string</summary>
        public string uid;
        /// <summary>tag=1, type=integer</summary>
        public int item_id;
        /// <summary>tag=2, type=integer</summary>
        public int count;
        /// <summary>tag=3, type=integer</summary>
        public int position;
        /// <summary>tag=4, type=boolean</summary>
        public bool equipped;
        /// <summary>tag=5, type=string</summary>
        public string extra;
    }

    [System.Serializable]
    public class EffectEntry
    {
        /// <summary>tag=0, type=string</summary>
        public string type;
        /// <summary>tag=1, type=integer</summary>
        public int value;
    }

    [System.Serializable]
    public class ChatMessageEntry
    {
        /// <summary>tag=0, type=integer</summary>
        public int from_id;
        /// <summary>tag=1, type=string</summary>
        public string from_name;
        /// <summary>tag=2, type=string</summary>
        public string msg;
        /// <summary>tag=3, type=integer</summary>
        public int timestamp;
    }

    [System.Serializable]
    public class Package
    {
        /// <summary>tag=0, type=integer</summary>
        public int type;
        /// <summary>tag=1, type=integer</summary>
        public int session;
    }

    [System.Serializable]
    public class RankEntry
    {
        /// <summary>tag=0, type=integer</summary>
        public int rank;
        /// <summary>tag=1, type=integer</summary>
        public int player_id;
        /// <summary>tag=2, type=string</summary>
        public string nickname;
        /// <summary>tag=3, type=integer</summary>
        public int score;
    }

    // ======== C2S 请求/响应类型 ========

    /// <summary>tag=30, direction=c2s</summary>
    [System.Serializable]
    public class BagListResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
        /// <summary>tag=1, type=item_entry[]</summary>
        public List<ItemEntry> items;
        /// <summary>tag=2, type=integer</summary>
        public int gold;
        /// <summary>tag=3, type=integer</summary>
        public int capacity;
    }

    /// <summary>tag=31, direction=c2s</summary>
    [System.Serializable]
    public class BagAddRequest
    {
        /// <summary>tag=0, type=integer</summary>
        public int item_id;
        /// <summary>tag=1, type=integer</summary>
        public int count;
    }

    [System.Serializable]
    public class BagAddResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
        /// <summary>tag=1, type=item_entry[]</summary>
        public List<ItemEntry> items;
    }

    /// <summary>tag=32, direction=c2s</summary>
    [System.Serializable]
    public class BagRemoveRequest
    {
        /// <summary>tag=0, type=string</summary>
        public string uid;
        /// <summary>tag=1, type=integer</summary>
        public int count;
    }

    [System.Serializable]
    public class BagRemoveResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
    }

    /// <summary>tag=33, direction=c2s</summary>
    [System.Serializable]
    public class BagUseRequest
    {
        /// <summary>tag=0, type=string</summary>
        public string uid;
        /// <summary>tag=1, type=integer</summary>
        public int count;
    }

    [System.Serializable]
    public class BagUseResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
        /// <summary>tag=1, type=effect_entry[]</summary>
        public List<EffectEntry> effects;
    }

    /// <summary>tag=34, direction=c2s</summary>
    [System.Serializable]
    public class BagSortResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
        /// <summary>tag=1, type=item_entry[]</summary>
        public List<ItemEntry> items;
    }

    /// <summary>tag=40, direction=c2s</summary>
    [System.Serializable]
    public class ChatSendRequest
    {
        /// <summary>tag=0, type=integer</summary>
        public int channel;
        /// <summary>tag=1, type=integer</summary>
        public int target_id;
        /// <summary>tag=2, type=string</summary>
        public string msg;
    }

    [System.Serializable]
    public class ChatSendResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
    }

    /// <summary>tag=41, direction=c2s</summary>
    [System.Serializable]
    public class ChatHistoryRequest
    {
        /// <summary>tag=0, type=integer</summary>
        public int channel;
        /// <summary>tag=1, type=integer</summary>
        public int count;
    }

    [System.Serializable]
    public class ChatHistoryResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
        /// <summary>tag=1, type=chat_message_entry[]</summary>
        public List<ChatMessageEntry> messages;
    }

    /// <summary>tag=10, direction=c2s</summary>
    [System.Serializable]
    public class EnterSceneRequest
    {
        /// <summary>tag=0, type=integer</summary>
        public int scene_id;
    }

    [System.Serializable]
    public class EnterSceneResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
    }

    /// <summary>tag=11, direction=c2s</summary>
    [System.Serializable]
    public class MoveRequest
    {
        /// <summary>tag=0, type=integer</summary>
        public int x;
        /// <summary>tag=1, type=integer</summary>
        public int y;
    }


    /// <summary>tag=1, direction=c2s</summary>
    [System.Serializable]
    public class LoginRequest
    {
        /// <summary>tag=0, type=string</summary>
        public string account;
        /// <summary>tag=1, type=string</summary>
        public string password;
    }

    [System.Serializable]
    public class LoginResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
        /// <summary>tag=1, type=integer</summary>
        public int player_id;
        /// <summary>tag=2, type=string</summary>
        public string token;
        /// <summary>tag=3, type=string</summary>
        public string nickname;
        /// <summary>tag=4, type=integer</summary>
        public int level;
    }

    /// <summary>tag=2, direction=c2s</summary>
    [System.Serializable]
    public class RegisterRequest
    {
        /// <summary>tag=0, type=string</summary>
        public string account;
        /// <summary>tag=1, type=string</summary>
        public string password;
    }

    [System.Serializable]
    public class RegisterResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
        /// <summary>tag=1, type=integer</summary>
        public int player_id;
    }

    /// <summary>tag=50, direction=c2s</summary>
    [System.Serializable]
    public class RankTopRequest
    {
        /// <summary>tag=0, type=string</summary>
        public string board_type;
        /// <summary>tag=1, type=integer</summary>
        public int top_n;
    }

    [System.Serializable]
    public class RankTopResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
        /// <summary>tag=1, type=rank_entry[]</summary>
        public List<RankEntry> entries;
        /// <summary>tag=2, type=integer</summary>
        public int update_time;
    }

    /// <summary>tag=51, direction=c2s</summary>
    [System.Serializable]
    public class RankSelfRequest
    {
        /// <summary>tag=0, type=string</summary>
        public string board_type;
    }

    [System.Serializable]
    public class RankSelfResponse
    {
        /// <summary>tag=0, type=boolean</summary>
        public bool ok;
        /// <summary>tag=1, type=integer</summary>
        public int rank;
        /// <summary>tag=2, type=integer</summary>
        public int score;
        /// <summary>tag=3, type=integer</summary>
        public int total;
    }

    // ======== S2C 推送类型 ========

    /// <summary>tag=10, direction=s2c</summary>
    [System.Serializable]
    public class ChatNotifyResponse
    {
        /// <summary>tag=0, type=integer</summary>
        public int player_id;
        /// <summary>tag=1, type=string</summary>
        public string msg;
    }

    /// <summary>tag=11, direction=s2c</summary>
    [System.Serializable]
    public class ChatMessageResponse
    {
        /// <summary>tag=0, type=integer</summary>
        public int channel;
        /// <summary>tag=1, type=integer</summary>
        public int from_id;
        /// <summary>tag=2, type=string</summary>
        public string from_name;
        /// <summary>tag=3, type=string</summary>
        public string msg;
        /// <summary>tag=4, type=integer</summary>
        public int timestamp;
    }

    /// <summary>tag=1, direction=s2c</summary>
    [System.Serializable]
    public class ErrorResponse
    {
        /// <summary>tag=0, type=integer</summary>
        public int code;
        /// <summary>tag=1, type=string</summary>
        public string msg;
    }
}
