#!/usr/bin/env python3
"""
sprotogen — .sproto 代码生成器

从 server/proto/*.sproto 中解析协议定义，生成:
  - server/module/proto_stub.lua: 协议号常量 + handler 注册/分发系统

用法:
  python tools/sprotogen.py
"""

import os
import re
from collections import OrderedDict

PROTO_DIR = os.path.join(os.path.dirname(__file__), "..", "proto")
OUTPUT = os.path.join(os.path.dirname(__file__), "..", "server", "module", "proto_stub.lua")

# 协议定义正则: proto_name tag { ... }
PROTO_RE = re.compile(
    r'^(\w+)\s+(\d+)\s*\{',
    re.MULTILINE,
)


def parse_sproto(filename):
    """从 .sproto 文件中提取所有协议定义 {name, tag}"""
    with open(filename, encoding="utf-8") as f:
        text = f.read()
    protos = []
    for match in PROTO_RE.finditer(text):
        name, tag = match.group(1), int(match.group(2))
        protos.append((name, tag))
    return protos


def classify_file(filename):
    """根据文件名推断方向: c2s, s2c, public"""
    base = os.path.basename(filename)
    if "_c2s.sproto" in base:
        return "c2s"
    elif "_s2c.sproto" in base:
        return "s2c"
    return "public"


def get_module_name(filename):
    """提取模块名: bag_c2s.sproto -> bag"""
    base = os.path.basename(filename)
    for suffix in ["_c2s.sproto", "_s2c.sproto", "_public.sproto"]:
        if base.endswith(suffix):
            return base[: -len(suffix)]
    return base.replace(".sproto", "")


def main():
    # 收集所有协议
    # modules[module] = { c2s: [(name,tag)], s2c: [(name,tag)] }
    modules = OrderedDict()
    all_c2s = OrderedDict()  # name -> tag
    all_s2c = OrderedDict()

    for fname in sorted(os.listdir(PROTO_DIR)):
        if not fname.endswith(".sproto"):
            continue
        fpath = os.path.join(PROTO_DIR, fname)
        protos = parse_sproto(fpath)
        if not protos:
            continue

        mod = get_module_name(fname)
        direction = classify_file(fname)
        if direction not in ("c2s", "s2c"):
            continue

        modules.setdefault(mod, {"c2s": [], "s2c": []})
        for name, tag in protos:
            modules[mod][direction].append((name, tag))
            target = all_c2s if direction == "c2s" else all_s2c
            target[name] = tag

    # 生成 Lua 代码
    lines = []
    lines.append("-- auto-generated by tools/sprotogen.py -- do not edit")
    lines.append("")
    lines.append("local M = {}")
    lines.append("")

    # c2s 常量
    c2s_protos_by_module = OrderedDict()
    for mod, dirs in modules.items():
        for name, tag in dirs.get("c2s", []):
            c2s_protos_by_module.setdefault(mod, []).append((name, tag))

    if c2s_protos_by_module:
        lines.append("-- ======== c2s Protocol Tags ========")
        for mod, protos in c2s_protos_by_module.items():
            if protos:
                lines.append("-- " + mod)
                for name, tag in protos:
                    lines.append(f"M.{name.upper()} = {tag}")
                lines.append("")

    # s2c 常量
    s2c_protos_by_module = OrderedDict()
    for mod, dirs in modules.items():
        for name, tag in dirs.get("s2c", []):
            s2c_protos_by_module.setdefault(mod, []).append((name, tag))

    if s2c_protos_by_module:
        lines.append("-- ======== s2c Protocol Tags ========")
        for mod, protos in s2c_protos_by_module.items():
            if protos:
                lines.append("-- " + mod)
                for name, tag in protos:
                    lines.append(f"M.{name.upper()} = {tag}")
                lines.append("")

    # name → tag 映射（运行时字符串查找用）
    lines.append("-- ======== Name ↔ Tag Mapping ========")
    lines.append("local name_to_tag = {}")
    for mod, dirs in modules.items():
        for direction in ("c2s", "s2c"):
            for name, tag in dirs.get(direction, []):
                lines.append(f"name_to_tag[\"{name}\"] = {tag}")
    lines.append("M._name_to_tag = name_to_tag")
    lines.append("")

    # Handler Registry
    lines.append("-- ======== Handler Registry ========")
    lines.append("local handlers = {}")
    lines.append("")
    lines.append("function M.register(name, fn)")
    lines.append("    assert(type(name) == \"string\" and type(fn) == \"function\",")
    lines.append('        "proto.register: expected (string, function)")')
    lines.append("    handlers[name] = fn")
    lines.append("end")
    lines.append("")
    lines.append("function M.register_module(module_name, handler_table)")
    lines.append('    assert(type(handler_table) == "table",')
    lines.append('        "proto.register_module: expected table of handlers")')
    lines.append("    for name, fn in pairs(handler_table) do")
    lines.append('        assert(type(fn) == "function",')
    lines.append('            string.format("proto.register_module: handler \'%s\' must be a function", name))')
    lines.append("        handlers[name] = fn")
    lines.append("    end")
    lines.append("end")
    lines.append("")
    lines.append("function M.dispatch(name, ctx, ...)")
    lines.append("    local fn = handlers[name]")
    lines.append("    if fn then")
    lines.append("        return fn(ctx, ...)")
    lines.append("    end")
    lines.append('    return nil, "unknown protocol: " .. tostring(name)')
    lines.append("end")
    lines.append("")
    lines.append("function M.has_handler(name)")
    lines.append("    return handlers[name] ~= nil")
    lines.append("end")
    lines.append("")
    lines.append("return M")
    lines.append("")

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"[sprotogen] generated {OUTPUT}")
    print(f"  c2s: {len(all_c2s)} protocols, s2c: {len(all_s2c)} protocols")


if __name__ == "__main__":
    main()
