-- auto-generated by tools/export_config.py -- do not edit

local M = {}

M[1001] = {id = 1001, name = "小瓶HP药水", type = "consumable", sub_type = "hp_potion", quality = 1, stackable = true, max_stack = 99, sell_price = 10, use_effect = {hp = 50}, equip_slot = "", description = "恢复50点生命值"}
M[1002] = {id = 1002, name = "小瓶MP药水", type = "consumable", sub_type = "mp_potion", quality = 1, stackable = true, max_stack = 99, sell_price = 10, use_effect = {mp = 50}, equip_slot = "", description = "恢复50点魔法值"}
M[2001] = {id = 2001, name = "铁矿", type = "material", sub_type = "ore", quality = 1, stackable = true, max_stack = 999, sell_price = 5, equip_slot = "", description = "常见的铁矿石"}
M[3001] = {id = 3001, name = "铁剑", type = "equipment", sub_type = "sword", quality = 1, stackable = false, max_stack = 1, sell_price = 50, equip_slot = "weapon", attributes = {attack = 10}, description = "一把普通的铁剑"}
M[3002] = {id = 3002, name = "铁甲", type = "equipment", sub_type = "chest", quality = 1, stackable = false, max_stack = 1, sell_price = 80, equip_slot = "chest", attributes = {defense = 15}, description = "一件普通的铁甲"}

return M
